#!/usr/bin/env bash
set -euo pipefail
: "${REDIS_TEST_ADDR:?Set REDIS_TEST_ADDR to a disposable real Redis instance}"
test -z "$(gofmt -l cmd internal)"
go mod verify
go vet ./...
go test -race -count=1 ./...
go build ./...
govulncheck ./...
git diff --check
